name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2.0.0

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2.0.1

    - name: Restore Packages
      run: nuget restore AltController.sln
      continue-on-error: true

    - name: Build Project
      run: msbuild AltController/AltController.csproj /p:Configuration=Release /p:Platform="x86" /p:TargetFrameworkVersion=v4.8 /p:TargetFrameworkProfile=""

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: AltController-Custom-EXE
        path: |
          AltController/bin/x86/Release/
          AltController/bin/Release/
